### ISSUE TITLE
css and png are not generated

### ISSUE THREAD

**Issue by eddichen** [w0rm/gulp-svgfallback#11]
running v3.6.0 and recently updated to MacOSX Sierra, my svg fallback task is not generating the svg image or css anymore. They have been working previously and my only change has been to update the Mac OSX.

`/** svg fallback **/
gulp.task('svgfallback', ['svgstore'], function () {
    gulp.src(imagesOriginalDir + 'svg/*.svg', {base: 'svgfallback'})
        .pipe($.rename({prefix: 'no-svg .'}))
        .pipe($.svgfallback())
        .pipe(gulp.dest(imagesDir));
});`

**Comment by w0rm** [comment]
Hi @eddichen can you please check v4.0.1 and tell if it works for you?

**Comment by eddichen** [comment]
Ah yes, that works now! had to specify the version directly in the npm install command, previous attempts it only installed 3.0.2.

Thanks!

**Comment by w0rm** [comment]
@eddichen yeah, it's because I bumped the major version.
