### ISSUE TITLE
Security Vulnerability

### ISSUE THREAD

**Issue by jaybuddy** [w0rm/gulp-svgfallback#13]
I came across a vulnerability when running `npm audit`

The Lodash dependency is the culprit. I tried to push a branch with the updated package.json and got permission denied. 

https://nodesecurity.io/advisories/577

**Comment by w0rm** [comment]
@jaybuddy can you fork, push a branch there, then open a pull request?

**Comment by jaybuddy** [comment]
Sure thing

**Comment by w0rm** [comment]
@jaybuddy thanks, I just published gulp-svgfallback@5.0.1
